jobs:
  run:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./run/build

name: Workflow

on:
  schedule:
    - cron: "45 */2 * * *"
